boxplot(d$heures.tv, col = grey(0.8), main = "Nombre d'heures passées devant la télé par jour", ylab = "Heures") 
abline(h = median(d$heures.tv, na.rm = TRUE), col = "navy", lty = 2) 
text(1.35, median(d$heures.tv, na.rm = TRUE) + 0.15, "Médiane", col = "navy") 
Q1 <- quantile(d$heures.tv, probs = 0.25, na.rm = TRUE) 
abline(h = Q1, col = "darkred") 
text(1.35, Q1 + 0.15, "Q1 : premier quartile", col = "darkred", lty = 2) 
Q3 <- quantile(d$heures.tv, probs = 0.75, na.rm = TRUE) 
abline(h = Q3, col = "darkred") 
text(1.35, Q3 + 0.15, "Q3 : troisième quartile", col = "darkred", lty = 2) 
arrows(x0 = 0.7, y0 = quantile(d$heures.tv, probs = 0.75, na.rm = TRUE), x1 = 0.7, y1 = quantile(d$heures.tv, probs = 0.25, na.rm = TRUE), length = 0.1, code = 3) 
text(0.7, Q1 + (Q3 - Q1)/2 + 0.15, "h", pos = 2) 
mtext("L'écart inter-quartile h contient 50 % des individus", side = 1) 
abline(h = Q1 - 1.5 * (Q3 - Q1), col = "darkgreen") 
text(1.35, Q1 - 1.5 * (Q3 - Q1) + 0.15, "Q1 -1.5 h", col = "darkgreen", lty = 2) 
abline(h = Q3 + 1.5 * (Q3 - Q1), col = "darkgreen") 
text(1.35, Q3 + 1.5 * (Q3 - Q1) + 0.15, "Q3 +1.5 h", col = "darkgreen", lty = 2)

